language: node_js
node_js:
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: nsfSOCrA0YVM94SzVl6qXpkuyYo1mkyZ2iPPfx7YwBGPCMyAPkP1b4r4cWt5jwbFL5IEOdjKp8cxyqVb7Nt+3RE+lqa2MkoeSjtH8a9TqxbLDn3ifDmZQXZxjCUQmfTZgG3NsgA/wuVE9Yfk3SZyw5ysuKnJKVY5crL0P9moZh4OECXs/OIhDKEP5qVtZCHz9lvjw6zfh2jtdpFmwDwejZVew/KUfI/omN3Rdaxc6EatJF6CBRqR7PsKlLOYu5JmRn3+wflKrk3hYiSurQgtTIYdEbNNh6juEkt4JQBqD9Epl4spdRfsMsCBvht0IwpndVe9/vhMdd1B2miizvzpbzrD7JdrynCSdX+eUXnAtY2KRRWVcw2WtQ3P/82YSMNPQ9nUfqMx5xAsr9k2nzbufRLJn6YnlBvDAp0ktpfBsSjL+Wx80UUnaniYJaIXFx31vne6Wdf52P0bJbMMYZ80hskCxWsZV55YEwQUL7qCu8nMT4vmg+AGuwfSErLin0Dio7x6oPJY44MUpfBTqArKy/laUccda0T55a508AQnGWX7XM1RHxj8BlGBATcUjKULXkPo7V8S3ny7qmg/xWPPj7iGvV6T7D6s6/jvvz3538GbK3TbXkLZl4RUnoAUZKn8pKc0w0hfR3Alsg7HrqBbcVPqZ6JZVLQhdMmD4MJxIaY=
  app:
    master: jadeleaf-pos
  run:
    - "babel-node server/seed.js"
    - "webpack --config ./webpack-prod.config.js --progress --color"
