export default {
  SET_STATE: 'SET_STATE',
  TOGGLE_ORDER: 'TOGGLE_ORDER',
  LOAD_ORDERS: 'LOAD_ORDERS',
  LOAD_ITEMS: 'LOAD_ITEMS',
  ADD_ORDER: 'ADD_ORDER',
  CHANGE_ENTRY_STATUS: 'CHANGE_ENTRY_STATUS',
  ADD_ENTRIES_TO_ORDER: 'ADD_ENTRIES_TO_ORDER',
  SET_READY_FOR_BILL: 'SET_READY_FOR_BILL',
  OPEN: 'OPEN',
  DELIVERED: 'DELIVERED',
  CANCELED: 'CANCELED',
  CLOSED: 'CLOSED',
  READY_FOR_BILL: 'READY_FOR_BILL',
  ALL: 'ALL',
  COMPLETED: 'COMPLETED',
  NOW: '2015-01-01T10:00:00-0800'
};
