export default {
  SET_STATE: 'SET_STATE',
  TOGGLE_ORDER: 'TOGGLE_ORDER',
  LOAD_ORDERS: 'LOAD_ORDERS',
  LOAD_ITEMS: 'LOAD_ITEMS',
  OPEN: 'OPEN',
  DELIVERED: 'DELIVERED',
  CANCELED: 'CANCELED',
  CLOSED: 'CLOSED',
  READY_FOR_BILL: 'READY_FOR_BILL',
  ADD_ORDER: 'ADD_ORDER',
  ALL: 'ALL'
};
